version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "7070:7070" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - laravel
      - vuejs

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  laravel :
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8181:8181
    depends_on:
      - redis
    volumes:
      - ./api:/app

  vuejs:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 4040:80
    depends_on:
      - laravel
    volumes:
      - ./front:/app

  vuejs-dev:
    build:
      context: .
      dockerfile: dev/front/Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    volumes:
      - ./front:/app
    command: npm run dev

