services:
  vuejs-dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    command: npm run dev